# NumPy

Numeric Python

In [ ]:
rgb(255,0,0)

In [ ]:
3D

In [ ]:
nd
4d
3d
2d     .___|____.
1d     ._______.
0d    .

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
a.dtype   # -2 ** 31 to 2 ** 31

dtype('int64')

In [ ]:
uint8 - #unsigned integer (0 to 255)

In [ ]:
uint16 - # (0 to 65535)

In [9]:
a.shape

(3,)

In [10]:
a = np.array([np.arange(2), np.arange(2)])
print(a)

[[0 1]
 [0 1]]


In [11]:
a.shape

(2, 2)

In [10]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [11]:
np.array?

In [12]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [13]:
matrix[0]

array([1, 2, 3])

In [14]:
matrix[1]

array([4, 5, 6])

In [15]:
matrix[0,0]

1

In [16]:
matrix[0,2]

3

In [17]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
matrix[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
matrix[0:2,0:1]

array([[1],
       [4]])

In [20]:
matrix.shape

(3, 3)

In [21]:
matrix.size

9

In [22]:
matrix.ndim

2

In [23]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
a = np.vectorize(lambda i : i+10)

print(a(matrix))

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [26]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
np.max(matrix)

9

In [28]:
np.min(matrix)

1

In [29]:
np.max(matrix, axis = 0) #column

array([7, 8, 9])

In [30]:
np.max(matrix, axis = 1) #row

array([3, 6, 9])

In [32]:
x = np.arange(7, dtype='uint16')
x

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [33]:
x.dtype.itemsize  # bytes

2

In [34]:
x = np.arange(7, dtype='f')
x

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [35]:
x = np.arange(7, dtype='D')
x

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [36]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
#mean

print(np.mean(matrix))

5.0


In [38]:
print(np.var(matrix))

6.666666666666667


In [39]:
print(np.std(matrix))

2.581988897471611


In [40]:
# reshaping

In [14]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [16]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [17]:
print(matrix.reshape(9))

[1 2 3 4 5 6 7 8 9]


In [18]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])